#!/usr/bin/env python3
'''
combine <first_array> <second_array>

returns a combined and sorted array from two arrays

  first_array    json formatted array of numbers
  second_array   json formatted array of numbers
'''
import sys
import json
from typing import List, Union


def parse(arg: str):
    try:
        parsed = json.loads(arg)
    except json.JSONDecodeError:
        raise TypeError(f'unable to parse argument: {arg}')

    if type(parsed) != list:
        raise TypeError(f'{arg} must be an array')

    if any([type(_) not in (float, int) for _ in parsed]):
        raise TypeError(f'{arg} must only contain numbers')

    return parsed


def format(item: List[Union[float, int]]):
    return json.dumps(item)


def combine(a: List[Union[float, int]], b: List[Union[float, int]]):
    return(sorted(a + b))


def main(args: List[str]):
    try:
        if len(args) != 3:
            raise RuntimeError(
                f'requires 2 arguments but {len(args)} were given')

        print(format(combine(parse(args[1]), parse(args[2]))))

    except (TypeError, RuntimeError) as e:
        print(str(e))
        print(__doc__)


if __name__ == '__main__':
    main(sys.argv)
