#!/usr/bin/env python3
'''
combine <a> <b>

returns a combined and sorted array composed of arrays a and b

  a    json formatted array of numbers
  b    json formatted array of numbers
'''
import sys
import json
from typing import List


def parse(arg: str):
    parsed = json.loads(arg)

    if type(parsed) != list:
        raise TypeError(f'{arg} must be an array')

    if any([type(_) != float for _ in parsed]):
        raise TypeError(f'{arg} must only contain numbers')


def combine(a: List[float], b: List[float]):
    pass


def main(args: List[str]):
    if len()

    a = parse(args[1])
    b = parse(args[2])


if __name__ == '__main__':
    main(sys.argv)
