#!/usr/bin/env bash
set -eu -o pipefail

# Lint and Test
docker build . \
  --tag ci \
  --file ci.Dockerfile
docker run ci

# Run semantic release to automatically version
npm ci
git_repo="https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
node_modules/.bin/semantic-release --repository-url="${git_repo}"

version=$(git tag --points-at HEAD)
if [[ -z "${version}" ]]; then
  # No new version to release
  exit 0
fi

# Build and publish
docker_repo="mgauthiere/combine"
commit="sha-$(git rev-parse --short HEAD)"
echo "${DOCKER_PASSWORD}" |
docker login \
  --password-stdin \
  --username "${DOCKER_USERNAME}"
docker build . \
  --tag "${docker_repo}:latest" \
  --tag "${docker_repo}:${version}" \
  --tag "${docker_repo}:${commit}"
docker push "${docker_repo}:latest"
docker push "${docker_repo}:${version}"
docker push "${docker_repo}:${commit}"
