#!/usr/bin/env bash
set -eu -o pipefail

test -n "${GITHUB_USERNAME}"
test -n "${GITHUB_TOKEN}"
test -n "${GITHUB_REPOSITORY}"

repo_url="https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"

npm ci
node_modules/.bin/semantic-release --repository-url "${repo_url}"

version=$(jq -r ".version" < package.json)
if [[ "${version}" == "0.0.0" ]]; then
    echo "No new version was released, aborting"
    exit 0
fi