name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Dependencies
      run: -|
        pip3 install setuptools &&
        pip3 install -r requirements.txt

    - name: Lint
      run: ./lint

    - name: test
      run: -|
        echo "no tests yet"

    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        username: "${DOCKERHUB_USERNAME}"
        password: "${DOCKERHUB_ACCESS_TOKEN}"
        repository: combine
        tags: "${SEMANTIC_VERSION},latest"
        tag_with_ref: yes
        tag_with_sha: yes
        build_args: ''
        push: yes
